import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout/Layout'
import styles from '../styles/Home.module.scss'
import backgroundDesk from '../public/assets/home/background-home-desktop.jpg'

export default function Home() {
  return (
   <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout backgroundImage={'/home/background-home-desktop.jpg'}>

      <h1>Ddddd</h1>

      </Layout>

     
    </>
  )
}
