import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout/Layout'
import styles from '../styles/Home.module.scss'
import backgroundDesk from '../public/assets/home/background-home-desktop.jpg'

export default function Home() {
  return (
   <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <section>

     <h5>SO, YOU WANT TO TRAVEL TO</h5>
     <h1>SPACE</h1>
     <p>Let’s face it; if you want to go to space, you might as well genuinely go to outer space and not hover kind of on the edge of it. Well sit back, and relax because we’ll give you a truly out of this world experience!</p>
     </section>
     <section>
      <div>EXPLORE</div>
     </section>
     
 
    </>
  )
}
